from package_test.test import Test

test1 = Test(1, "Firstly,")
answer1 = test1.write_test_info()
print(f"the next test is: {answer1}")
test2 = Test(2, "Secondly,")
answer2 = test2.write_test_info()
print(f"the next test is: {answer2}")
test3 = Test(3, "Thirdly,")
answer3 = test3.write_test_info()
print(f"the next test is: {answer3}")
test4 = Test(4, "Fourthly")
answer4 = test4.write_test_info()
print(f"the next test is: {answer4}")
test5 = Test(5, 'Test 5')
answer5 = test5.write_test_info()
print(f"the next test is: {answer5}")
